# Agent Configuration for Real Estate AI Agent System

# Legal Agent Configuration
legal_agent:
  name: "Legal Analysis Agent"
  description: "Specializes in legal analysis, contract review, and compliance checking"
  model: "gpt-4"
  temperature: 0.1
  max_tokens: 4000
  timeout: 60
  max_retries: 3
  enabled: true
  version: "1.0.0"
  
  # Legal-specific settings
  legal_knowledge_sources:
    - "federal_regulations"
    - "state_laws"
    - "local_ordinances"
    - "case_law"
    - "contract_templates"
  
  compliance_checking:
    enabled: true
    check_federal: true
    check_state: true
    check_local: true
    auto_update: true

# Financial Agent Configuration
financial_agent:
  name: "Financial Modeling Agent"
  description: "Specializes in financial analysis, investment calculations, and risk assessment"
  model: "claude-3-sonnet"
  temperature: 0.2
  max_tokens: 6000
  timeout: 90
  max_retries: 3
  enabled: true
  version: "1.0.0"
  
  # Financial-specific settings
  financial_models:
    - "cash_flow_analysis"
    - "investment_return_calculation"
    - "risk_assessment"
    - "market_analysis"
    - "tax_implications"
  
  data_sources:
    - "market_data_feeds"
    - "tax_records"
    - "financial_reports"
    - "economic_indicators"

# Market Agent Configuration
market_agent:
  name: "Market Research Agent"
  description: "Specializes in property valuation, market trends, and comparative analysis"
  model: "gpt-4"
  temperature: 0.15
  max_tokens: 5000
  timeout: 75
  max_retries: 3
  enabled: true
  version: "1.0.0"
  
  # Market-specific settings
  market_data_sources:
    - "mls_systems"
    - "public_records"
    - "market_reports"
    - "zillow_api"
    - "redfin_api"
    - "realtor_api"
  
  analysis_types:
    - "comparable_sales"
    - "market_trends"
    - "price_forecasting"
    - "neighborhood_analysis"
    - "investment_opportunities"

# Document Agent Configuration
document_agent:
  name: "Document Processing Agent"
  description: "Specializes in document processing, contract generation, and record management"
  model: "claude-3-sonnet"
  temperature: 0.1
  max_tokens: 8000
  timeout: 120
  max_retries: 3
  enabled: true
  version: "1.0.0"
  
  # Document-specific settings
  supported_formats:
    - "pdf"
    - "docx"
    - "txt"
    - "html"
    - "json"
    - "xml"
  
  processing_capabilities:
    - "text_extraction"
    - "contract_generation"
    - "document_classification"
    - "data_extraction"
    - "format_conversion"

# User Agent Configuration
user_agent:
  name: "User Interaction Agent"
  description: "Specializes in customer service, query handling, and personalized recommendations"
  model: "gpt-4"
  temperature: 0.3
  max_tokens: 3000
  timeout: 45
  max_retries: 3
  enabled: true
  version: "1.0.0"
  
  # User-specific settings
  interaction_modes:
    - "chat"
    - "voice"
    - "email"
    - "web_form"
  
  personalization:
    enabled: true
    user_profiles: true
    preference_learning: true
    recommendation_engine: true

# System-wide Configuration
system:
  max_concurrent_agents: 10
  health_check_interval: 30
  system_timeout: 300
  log_level: "INFO"
  
  # Communication settings
  communication:
    message_timeout: 60
    retry_attempts: 3
    broadcast_enabled: true
  
  # Security settings
  security:
    authentication_required: true
    encryption_enabled: true
    audit_logging: true
  
  # Performance settings
  performance:
    cache_enabled: true
    cache_ttl: 3600
    rate_limiting: true
    max_requests_per_minute: 100
